# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d918de3ba86e48ec10edc35ef1000e5cf5a4c21947592db5e0df6fab2349d0d9c5cad38996c76fbb64727d4df60ae1a50ca1628b3dd29fc977256d80fd0d479f

test:
  secret_key_base: 48ccd93494c83c5a8a26f09cb1743205fcf80fb8ed3bde50e98d2cf7f9eeec7319dd575af4309e5dd82a27a71fd55e3fe74ee3273f375a2a75ce761fd39e9f03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
